target 'GDICoreDataKit', :exclusive => true do
  pod "GDICoreDataKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "GDICoreDataKit", :path => "../"
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
